apiVersion : apps/v1beta1
kind: Deployment
metadata:
  name: shiguptgotemp 
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: shiguptgotemp 
    spec:
      containers:
        - name: shiguptgotemp 
          image: divman.azurecr.io/shiguptgotemp
          ports:
          - containerPort: 80